### ISSUE TITLE
CMFs data error

### ISSUE THREAD

**Issue by studioadrienlucca** [ksmet1977/CRI_IES_RfRg#1]
Hi Kevin,

in your excel file there's an error in the 2 degree CMFs.
The value for z_bar at 380 nm is 0,000645 while it should be 0,00645

don't ask me how I found out...

Thanks for the TM30-15 algorithm, works great!

**Comment by studioadrienlucca** [comment]
It's also true at 630, 635, 640, 645 nm, the values are 10 times too high

**Comment by studioadrienlucca** [comment]
And the x_bar at 765 should be 0.000117 but it is 0.000177

**Comment by ksmet1977** [comment]
Thanks for letting me know, I'll check those files and others. I'm not sure why the values are wrong as I got those from cvrl.org a few years back. regards,KevinSent from my Samsung Galaxy smartphone.
-------- Original message --------From: studioadrienlucca <notifications@github.com> Date: 31/08/19  18:53  (GMT+01:00) To: ksmet1977/CRI_IES_RfRg <CRI_IES_RfRg@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [ksmet1977/CRI_IES_RfRg] CMFs data error (#1) Hi Kevin,
in your excel file there's an error in the 2 degree CMFs.
The value for z_bar at 380 nm is 0,000645 while it should be 0,00645
don't ask me how I found out...
Thanks for the TM30-15 algorithm, works great!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ksmet1977/CRI_IES_RfRg/issues/1?email_source=notifications\u0026email_token=ACS4LX2AKGTKRZQJXNZFLYLQHKOYVA5CNFSM4ISUGPSKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HITCNDQ",
"url": "https://github.com/ksmet1977/CRI_IES_RfRg/issues/1?email_source=notifications\u0026email_token=ACS4LX2AKGTKRZQJXNZFLYLQHKOYVA5CNFSM4ISUGPSKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HITCNDQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by studioadrienlucca** [comment]
no problem, my pleasure!

**Comment by ksmet1977** [comment]
I have updated the CIE 1931 CMFs in all excell calculators. The error is also present in the official CIE Rf calculator downloadable from the CIE website (accessed 31/08/2019)! 
The error can at least be traced back to an early NIST CQS (v7.5) calculator created on 09/01/1999 and last updated on 09/02/2010. 
So my guess is that lots of calculators created in the past 10 or 20 years that used that CQS calculator or one of the other CQS 5nm calculators have that same problem, unless they explicitly updated the 1931 2° CMFs in those calculators. Please beware.
